import { TAccountType, TBank, TProvider } from 'database/types/index';

export const Account_Type: TAccountType[] = [
  {
    id: '1',
    name: 'Tiền mặt',
    value: 'cash',
    icon: 'cash',
  },
  {
    id: '2',
    name: 'Tài khoản ngân hàng',
    value: 'bank',
    icon: 'bank',
  },
  {
    id: '3',
    name: 'Thẻ tín dụng',
    value: 'credit',
    icon: 'credit',
  },
  {
    id: '4',
    name: 'Tài khoản đầu tư',
    value: 'investment',
    icon: 'investment',
  },
  {
    id: '5',
    name: 'Ví điện tử',
    value: 'eWallet',
    icon: 'eWallet',
  },
  {
    id: '6',
    name: 'Khác',
    value: 'other',
    icon: 'money',
  },
];

export const Provider: TProvider[] = [
  {
    id: '1',
    name: 'Shopee Pay',
    value: 'shopeepay',
    icon: 'shopeepay',
  },
  {
    id: '2',
    name: 'Viettel Pay',
    value: 'viettelpay',
    icon: 'viettelpay',
  },
  {
    id: '3',
    name: 'Zalo Pay',
    value: 'zalopay',
    icon: 'zalopay',
  },
  {
    id: '4',
    name: 'Momo',
    value: 'momo',
    icon: 'momo',
  },
  {
    id: '5',
    name: 'VNPT Pay',
    value: 'vnptpay',
    icon: 'vnptpay',
  },
];

export const Bank: TBank[] = [
  {
    id: '1',
    name: 'NH TMCP Ngoai Thuong VN',
    value: 'VCB',
    shortName: 'VietcomBank',
    icon: require('assets/images/banks/VCB.png'),
  },
  {
    id: '2',
    name: 'NH TMCP Cong Thuong VN',
    value: 'CTG',
    shortName: 'VietinBank',
    icon: require('assets/images/banks/CTG.png'),
  },
  {
    id: '3',
    name: 'NH TMCP Ky Thuong VN',
    value: 'TCB',
    shortName: 'Techcombank',
    icon: require('assets/images/banks/TCB.png'),
  },
  {
    id: '4',
    name: 'NH TMCP Dau Tu va Phat Trien VN',
    value: 'BIDV',
    shortName: 'BIDV',
    icon: require('assets/images/banks/BIDV.png'),
  },
  {
    id: '5',
    name: 'NH Nong Nghiep va Phat Trien Nong Thon Viet Nam',
    value: 'VARB',
    shortName: 'AgriBank',
    icon: require('assets/images/banks/VARB.png'),
  },
  {
    id: '6',
    name: 'Ngan hang Thuong Mai Co Phan Quoc Dan',
    value: 'NVB',
    shortName: 'Navibank',
    icon: require('assets/images/banks/NVB.png'),
  },
  {
    id: '7',
    name: 'NH TMCP Sai Gon Thuong Tin',
    value: 'STB',
    shortName: 'Sacombank',
    icon: require('assets/images/banks/STB.png'),
  },
  {
    id: '8',
    name: 'NH TMCP A Chau',
    value: 'ACB',
    shortName: 'ACB',
    icon: require('assets/images/banks/ACB.png'),
  },
  {
    id: '9',
    name: 'NH TMCP Quan Doi',
    value: 'MB',
    shortName: 'MBBank',
    icon: require('assets/images/banks/MB.png'),
  },
  {
    id: '10',
    name: 'NH TMCP Tien Phong',
    value: 'TPB',
    shortName: 'TPBank',
    icon: require('assets/images/banks/TPB.png'),
  },
  {
    id: '11',
    name: 'NH TNHH MTV Shinhan VN',
    value: 'SVB',
    shortName: 'Shinhan Bank',
    icon: require('assets/images/banks/SVB.png'),
  },
  {
    id: '12',
    name: 'NH TMCP Quoc Te VN',
    value: 'VIB',
    shortName: 'VIB Bank',
    icon: require('assets/images/banks/VIB.png'),
  },
  {
    id: '13',
    name: 'NH TMCP Viet Nam Thinh Vuong',
    value: 'VPB',
    shortName: 'VPBank',
    icon: require('assets/images/banks/VPB.png'),
  },
  {
    id: '14',
    name: 'NH TMCP Sai Gon Ha Noi',
    value: 'SHB',
    shortName: 'SHB',
    icon: require('assets/images/banks/SHB.png'),
  },
  {
    id: '15',
    name: 'NH TMCP Xuat Nhap khau VN',
    value: 'EIB',
    shortName: 'Eximbank',
    icon: require('assets/images/banks/EIB.png'),
  },
  {
    id: '16',
    name: 'NH TMCP Bao Viet',
    value: 'BVB',
    shortName: 'BaoVietBank',
    icon: require('assets/images/banks/BVB.png'),
  },
  {
    id: '17',
    name: 'NH TMCP Ban Viet',
    value: 'VCCB',
    shortName: 'VietcapitalBank',
    icon: require('assets/images/banks/VCCB.png'),
  },
  {
    id: '18',
    name: 'NH TMCP Sai Gon',
    value: 'SCB',
    shortName: 'SCB',
    icon: require('assets/images/banks/SCB.png'),
  },
  {
    id: '19',
    name: 'NH Lien Doanh Viet Nga',
    value: 'VRB',
    shortName: 'VietNam - Russia Bank',
    icon: require('assets/images/banks/VRB.png'),
  },
  {
    id: '20',
    name: 'NH TMCP An Binh',
    value: 'ABB',
    shortName: 'ABBank',
    icon: require('assets/images/banks/ABB.png'),
  },
  {
    id: '21',
    name: 'NH TMCP Dai Chung VN',
    value: 'PVCB',
    shortName: 'PVCombank',
    icon: require('assets/images/banks/PVCB.png'),
  },
  {
    id: '22',
    name: 'NH TM TNHH MTV Dai Duong',
    value: 'OJB',
    shortName: 'OceanBank',
    icon: require('assets/images/banks/OJB.png'),
  },
  {
    id: '23',
    name: 'NH TMCP Nam A',
    value: 'NAB',
    shortName: 'NamA bank',
    icon: require('assets/images/banks/NAB.png'),
  },
  {
    id: '24',
    name: 'NH TMCP Phat Trien TP HCM',
    value: 'HDB',
    shortName: 'HDBank',
    icon: require('assets/images/banks/HDB.png'),
  },
  {
    id: '25',
    name: 'NH TMCP Viet Nam Thuong Tin',
    value: 'VB',
    shortName: 'VietBank',
    icon: require('assets/images/banks/VB.png'),
  },
  {
    id: '26',
    name: 'Công ty Tài chính Cổ Phần Tín Việt',
    value: 'CFC',
    shortName: 'VietCredit',
    icon: require('assets/images/banks/CFC.png'),
  },
  {
    id: '27',
    name: 'NH TNHH MTV Public VN',
    value: 'PBVN',
    shortName: 'Public bank',
    icon: require('assets/images/banks/PBVN.png'),
  },
  {
    id: '28',
    name: 'NH TNHH MTV Hongleong VN',
    value: 'HLB',
    shortName: 'Hongleong Bank',
    icon: require('assets/images/banks/HLB.png'),
  },
  {
    id: '29',
    name: 'NH TMCP Xang Dau Petrolimex',
    value: 'PGB',
    shortName: 'PG Bank',
    icon: require('assets/images/banks/PGB.png'),
  },
  {
    id: '30',
    name: 'NH Hop Tac',
    value: 'COB',
    shortName: 'Co.op Bank',
    icon: require('assets/images/banks/COB.png'),
  },
  {
    id: '31',
    name: 'NH TNHH MTV CIMB Viet Nam',
    value: 'CIMB',
    shortName: 'CIMB',
    icon: require('assets/images/banks/CIMB.png'),
  },
  {
    id: '32',
    name: 'NH TNHH Indovina',
    value: 'IVB',
    shortName: 'Indovina',
    icon: require('assets/images/banks/IVB.png'),
  },
  {
    id: '33',
    name: 'NH TMCP Dong A',
    value: 'DAB',
    shortName: 'DongABank',
    icon: require('assets/images/banks/DAB.png'),
  },
  {
    id: '34',
    name: 'NH TM TNHH MTV Dau Khi Toan Cau',
    value: 'GPB',
    shortName: 'GPBank',
    icon: require('assets/images/banks/GPB.png'),
  },
  {
    id: '35',
    name: 'NH TMCP Bac A',
    value: 'NASB',
    shortName: 'BacABank',
    icon: require('assets/images/banks/NASB.png'),
  },
  {
    id: '36',
    name: 'NH TMCP Viet A',
    value: 'VAB',
    shortName: 'VietABank',
    icon: require('assets/images/banks/VAB.png'),
  },
  {
    id: '37',
    name: 'NH TMCP Sai Gon Cong Thuong',
    value: 'SGB',
    shortName: 'SaigonBank',
    icon: require('assets/images/banks/SGB.png'),
  },
  {
    id: '38',
    name: 'NH TMCP Hang Hai VN',
    value: 'MSB',
    shortName: 'Maritime Bank',
    icon: require('assets/images/banks/MSB.png'),
  },
  {
    id: '39',
    name: 'NH TMCP Buu Dien Lien Viet',
    value: 'LPB',
    shortName: 'LienVietPostBank',
    icon: require('assets/images/banks/LPB.png'),
  },
  {
    id: '40',
    name: 'NH TMCP Kien Long',
    value: 'KLB',
    shortName: 'KienLongBank',
    icon: require('assets/images/banks/KLB.png'),
  },
  {
    id: '41',
    name: 'NH Cong Nghiep Han Quoc CN Ha Noi',
    value: 'IBKHN',
    shortName: 'IBK - Ha Noi',
    icon: require('assets/images/banks/IBKHN.png'),
  },
  {
    id: '42',
    name: 'NH Wooribank',
    value: 'WOO',
    shortName: 'Woori bank',
    icon: require('assets/images/banks/WOO.png'),
  },
  {
    id: '43',
    name: 'NH TMCP Dong Nam A',
    value: 'SEAB',
    shortName: 'SeABank',
    icon: require('assets/images/banks/SEAB.png'),
  },
  {
    id: '44',
    name: 'NH TNHH MTV United Overseas Bank',
    value: 'UOB',
    shortName: 'UOB',
    icon: require('assets/images/banks/UOB.png'),
  },
  {
    id: '45',
    name: 'NH TMCP Phuong Dong',
    value: 'OCB',
    shortName: 'OCB',
    icon: require('assets/images/banks/OCB.png'),
  },
  {
    id: '46',
    name: 'Cong ty Tai chinh TNHH MTV Mirae Asset (Viet Nam)',
    value: 'MAFC',
    shortName: 'Mirae Asset',
    icon: require('assets/images/banks/MAFC.png'),
  },
  {
    id: '47',
    name: 'Ngan hang Keb Hana',
    value: 'KEBHANA',
    shortName: 'Keb Hana - Ho Chi Minh',
    icon: require('assets/images/banks/KEBHANA.png'),
  },
  {
    id: '49',
    name: 'Standard Chartered',
    value: 'STANDARD',
    shortName: 'Standard Chartered',
    icon: require('assets/images/banks/STANDARD.png'),
  },
  {
    id: '50',
    name: 'NH So CAKE by VPBank',
    value: 'CAKE',
    shortName: 'CAKE',
    icon: require('assets/images/banks/CAKE.png'),
  },
  {
    id: '51',
    name: 'NH So Ubank by VPBank',
    value: 'Ubank',
    shortName: 'Ubank',
    icon: require('assets/images/banks/Ubank.png'),
  },
  {
    id: '52',
    name: 'NH Nonghyup - Chi nhanh Ha Noi',
    value: 'NonghyupBankHN',
    shortName: 'Nonghyup Bank - HN',
    icon: require('assets/images/banks/NonghyupBankHN.png'),
  },
  {
    id: '53',
    name: 'NH Kookmin - Chi nhanh Ha Noi',
    value: 'KBHN',
    shortName: 'Kookmin - HN',
    icon: require('assets/images/banks/KBHN.png'),
  },
  {
    id: '54',
    name: 'NH Kookmin - Chi nhanh TP. HCM',
    value: 'KBHCM',
    shortName: 'Kookmin - HCM',
    icon: require('assets/images/banks/KBHCM.png'),
  },
  {
    id: '55',
    name: 'NH DBS - Chi nhanh TP. HCM',
    value: 'DBSHCM',
    shortName: 'DBS - HCM',
    icon: require('assets/images/banks/DBSHCM.png'),
  },
  {
    id: '56',
    name: 'NH TM TNHH MTV Xay Dung Viet Nam',
    value: 'CBBank',
    shortName: 'CBBank',
    icon: require('assets/images/banks/CBBank.png'),
  },
  {
    id: '57',
    name: 'NH Dai chung TNHH Kasikornbank - Chi nhanh TP. HCM',
    value: 'KBankHCM',
    shortName: 'KBank - HCM',
    icon: require('assets/images/banks/KBankHCM.png'),
  },
  {
    id: '58',
    name: 'NH TNHH MTV HSBC Viet Nam',
    value: 'HSBC',
    shortName: 'HSBC',
    icon: require('assets/images/banks/HSBC.png'),
  },
];
