import { TAccountType, TProvider } from 'src/types/models';

// export const STORAGE_KEY_TOKEN = 'TOKEN';
// export const STORAGE_KEY_APP_THEME = 'APP_THEME';
// export const KANA_FULL_HALF_MAP = {
//   ガ: 'ｶﾞ',
//   ギ: 'ｷﾞ',
//   グ: 'ｸﾞ',
//   ゲ: 'ｹﾞ',
//   ゴ: 'ｺﾞ',
//   ザ: 'ｻﾞ',
//   ジ: 'ｼﾞ',
//   ズ: 'ｽﾞ',
//   ゼ: 'ｾﾞ',
//   ゾ: 'ｿﾞ',
//   ダ: 'ﾀﾞ',
//   ヂ: 'ﾁﾞ',
//   ヅ: 'ﾂﾞ',
//   デ: 'ﾃﾞ',
//   ド: 'ﾄﾞ',
//   バ: 'ﾊﾞ',
//   ビ: 'ﾋﾞ',
//   ブ: 'ﾌﾞ',
//   ベ: 'ﾍﾞ',
//   ボ: 'ﾎﾞ',
//   パ: 'ﾊﾟ',
//   ピ: 'ﾋﾟ',
//   プ: 'ﾌﾟ',
//   ペ: 'ﾍﾟ',
//   ポ: 'ﾎﾟ',
//   ヴ: 'ｳﾞ',
//   ヷ: 'ﾜﾞ',
//   ヺ: 'ｦﾞ',
//   ア: 'ｱ',
//   イ: 'ｲ',
//   ウ: 'ｳ',
//   エ: 'ｴ',
//   オ: 'ｵ',
//   カ: 'ｶ',
//   キ: 'ｷ',
//   ク: 'ｸ',
//   ケ: 'ｹ',
//   コ: 'ｺ',
//   サ: 'ｻ',
//   シ: 'ｼ',
//   ス: 'ｽ',
//   セ: 'ｾ',
//   ソ: 'ｿ',
//   タ: 'ﾀ',
//   チ: 'ﾁ',
//   ツ: 'ﾂ',
//   テ: 'ﾃ',
//   ト: 'ﾄ',
//   ナ: 'ﾅ',
//   ニ: 'ﾆ',
//   ヌ: 'ﾇ',
//   ネ: 'ﾈ',
//   ノ: 'ﾉ',
//   ハ: 'ﾊ',
//   ヒ: 'ﾋ',
//   フ: 'ﾌ',
//   ヘ: 'ﾍ',
//   ホ: 'ﾎ',
//   マ: 'ﾏ',
//   ミ: 'ﾐ',
//   ム: 'ﾑ',
//   メ: 'ﾒ',
//   モ: 'ﾓ',
//   ヤ: 'ﾔ',
//   ユ: 'ﾕ',
//   ヨ: 'ﾖ',
//   ラ: 'ﾗ',
//   リ: 'ﾘ',
//   ル: 'ﾙ',
//   レ: 'ﾚ',
//   ロ: 'ﾛ',
//   ワ: 'ﾜ',
//   ヲ: 'ｦ',
//   ン: 'ﾝ',
//   ァ: 'ｧ',
//   ィ: 'ｨ',
//   ゥ: 'ｩ',
//   ェ: 'ｪ',
//   ォ: 'ｫ',
//   ッ: 'ｯ',
//   ャ: 'ｬ',
//   ュ: 'ｭ',
//   ョ: 'ｮ',
//   '。': '｡',
//   '、': '､',
//   ー: 'ｰ',
//   '「': '｢',
//   '」': '｣',
//   '・': '･',
//   '１': '1',
//   '２': '2',
//   '３': '3',
//   '４': '4',
//   '５': '5',
//   '６': '6',
//   '７': '7',
//   '８': '8',
//   '９': '9',
//   '０': '0',
// } as Record<string, string>;

export const logBoxIgnore = [
  "Module RNCColorPicker requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.",
];

export const CREATE_MODE = 'create';

export const Account_Type: TAccountType[] = [
  {
    _id: '1',
    name: 'Tiền mặt',
    value: 'cash',
    icon: 'cash',
  },
  {
    _id: '2',
    name: 'Tài khoản ngân hàng',
    value: 'bank',
    icon: 'bank',
  },
  {
    _id: '3',
    name: 'Thẻ tín dụng',
    value: 'credit',
    icon: 'credit',
  },
  {
    _id: '4',
    name: 'Tài khoản đầu tư',
    value: 'investment',
    icon: 'investment',
  },
  {
    _id: '5',
    name: 'Ví điện tử',
    value: 'eWallet',
    icon: 'eWallet',
  },
  {
    _id: '6',
    name: 'Khác',
    value: 'other',
    icon: 'money',
  },
];

export const Provider: TProvider[] = [
  {
    _id: '1',
    name: 'Shopee Pay',
    value: 'shopeepay',
    icon: 'shopeepay',
  },
  {
    _id: '2',
    name: 'Viettel Pay',
    value: 'viettelpay',
    icon: 'viettelpay',
  },
  {
    _id: '3',
    name: 'Zalo Pay',
    value: 'zalopay',
    icon: 'zalopay',
  },
  {
    _id: '4',
    name: 'Momo',
    value: 'momo',
    icon: 'momo',
  },
  {
    _id: '5',
    name: 'VNPT Pay',
    value: 'vnptpay',
    icon: 'vnptpay',
  },
];
