import { TAccountType, TProvider, TBank } from 'src/types/models';

// export const STORAGE_KEY_TOKEN = 'TOKEN';
// export const STORAGE_KEY_APP_THEME = 'APP_THEME';
// export const KANA_FULL_HALF_MAP = {
//   ガ: 'ｶﾞ',
//   ギ: 'ｷﾞ',
//   グ: 'ｸﾞ',
//   ゲ: 'ｹﾞ',
//   ゴ: 'ｺﾞ',
//   ザ: 'ｻﾞ',
//   ジ: 'ｼﾞ',
//   ズ: 'ｽﾞ',
//   ゼ: 'ｾﾞ',
//   ゾ: 'ｿﾞ',
//   ダ: 'ﾀﾞ',
//   ヂ: 'ﾁﾞ',
//   ヅ: 'ﾂﾞ',
//   デ: 'ﾃﾞ',
//   ド: 'ﾄﾞ',
//   バ: 'ﾊﾞ',
//   ビ: 'ﾋﾞ',
//   ブ: 'ﾌﾞ',
//   ベ: 'ﾍﾞ',
//   ボ: 'ﾎﾞ',
//   パ: 'ﾊﾟ',
//   ピ: 'ﾋﾟ',
//   プ: 'ﾌﾟ',
//   ペ: 'ﾍﾟ',
//   ポ: 'ﾎﾟ',
//   ヴ: 'ｳﾞ',
//   ヷ: 'ﾜﾞ',
//   ヺ: 'ｦﾞ',
//   ア: 'ｱ',
//   イ: 'ｲ',
//   ウ: 'ｳ',
//   エ: 'ｴ',
//   オ: 'ｵ',
//   カ: 'ｶ',
//   キ: 'ｷ',
//   ク: 'ｸ',
//   ケ: 'ｹ',
//   コ: 'ｺ',
//   サ: 'ｻ',
//   シ: 'ｼ',
//   ス: 'ｽ',
//   セ: 'ｾ',
//   ソ: 'ｿ',
//   タ: 'ﾀ',
//   チ: 'ﾁ',
//   ツ: 'ﾂ',
//   テ: 'ﾃ',
//   ト: 'ﾄ',
//   ナ: 'ﾅ',
//   ニ: 'ﾆ',
//   ヌ: 'ﾇ',
//   ネ: 'ﾈ',
//   ノ: 'ﾉ',
//   ハ: 'ﾊ',
//   ヒ: 'ﾋ',
//   フ: 'ﾌ',
//   ヘ: 'ﾍ',
//   ホ: 'ﾎ',
//   マ: 'ﾏ',
//   ミ: 'ﾐ',
//   ム: 'ﾑ',
//   メ: 'ﾒ',
//   モ: 'ﾓ',
//   ヤ: 'ﾔ',
//   ユ: 'ﾕ',
//   ヨ: 'ﾖ',
//   ラ: 'ﾗ',
//   リ: 'ﾘ',
//   ル: 'ﾙ',
//   レ: 'ﾚ',
//   ロ: 'ﾛ',
//   ワ: 'ﾜ',
//   ヲ: 'ｦ',
//   ン: 'ﾝ',
//   ァ: 'ｧ',
//   ィ: 'ｨ',
//   ゥ: 'ｩ',
//   ェ: 'ｪ',
//   ォ: 'ｫ',
//   ッ: 'ｯ',
//   ャ: 'ｬ',
//   ュ: 'ｭ',
//   ョ: 'ｮ',
//   '。': '｡',
//   '、': '､',
//   ー: 'ｰ',
//   '「': '｢',
//   '」': '｣',
//   '・': '･',
//   '１': '1',
//   '２': '2',
//   '３': '3',
//   '４': '4',
//   '５': '5',
//   '６': '6',
//   '７': '7',
//   '８': '8',
//   '９': '9',
//   '０': '0',
// } as Record<string, string>;

export const logBoxIgnore = [
  "Module RNCColorPicker requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.",
];

export const CREATE_MODE = 'create';

export const Account_Type: TAccountType[] = [
  {
    _id: '1',
    name: 'Tiền mặt',
    value: 'cash',
    icon: 'cash',
  },
  {
    _id: '2',
    name: 'Tài khoản ngân hàng',
    value: 'bank',
    icon: 'bank',
  },
  {
    _id: '3',
    name: 'Thẻ tín dụng',
    value: 'credit',
    icon: 'credit',
  },
  {
    _id: '4',
    name: 'Tài khoản đầu tư',
    value: 'investment',
    icon: 'investment',
  },
  {
    _id: '5',
    name: 'Ví điện tử',
    value: 'eWallet',
    icon: 'eWallet',
  },
  {
    _id: '6',
    name: 'Khác',
    value: 'other',
    icon: 'money',
  },
];

export const Provider: TProvider[] = [
  {
    _id: '1',
    name: 'Shopee Pay',
    value: 'shopeepay',
    icon: 'shopeepay',
  },
  {
    _id: '2',
    name: 'Viettel Pay',
    value: 'viettelpay',
    icon: 'viettelpay',
  },
  {
    _id: '3',
    name: 'Zalo Pay',
    value: 'zalopay',
    icon: 'zalopay',
  },
  {
    _id: '4',
    name: 'Momo',
    value: 'momo',
    icon: 'momo',
  },
  {
    _id: '5',
    name: 'VNPT Pay',
    value: 'vnptpay',
    icon: 'vnptpay',
  },
];

export const Bank: TBank[] = [
  {
    _id: '17',
    name: 'Ngân hàng TMCP Công thương Việt Nam',
    value: 'ICB',
    shortName: 'VietinBank',
    icon: 'https://api.vietqr.io/img/ICB.png',
  },
  {
    _id: '43',
    name: 'Ngân hàng TMCP Ngoại Thương Việt Nam',
    value: 'VCB',
    shortName: 'Vietcombank',
    icon: 'https://api.vietqr.io/img/VCB.png',
  },
  {
    _id: '4',
    name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam',
    value: 'BIDV',
    shortName: 'BIDV',
    icon: 'https://api.vietqr.io/img/BIDV.png',
  },
  {
    _id: '42',
    name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam',
    value: 'VBA',
    shortName: 'Agribank',
    icon: 'https://api.vietqr.io/img/VBA.png',
  },
  {
    _id: '26',
    name: 'Ngân hàng TMCP Phương Đông',
    value: 'OCB',
    shortName: 'OCB',
    icon: 'https://api.vietqr.io/img/OCB.png',
  },
  {
    _id: '21',
    name: 'Ngân hàng TMCP Quân đội',
    value: 'MB',
    shortName: 'MBBank',
    icon: 'https://api.vietqr.io/img/MB.png',
  },
  {
    _id: '38',
    name: 'Ngân hàng TMCP Kỹ thương Việt Nam',
    value: 'TCB',
    shortName: 'Techcombank',
    icon: 'https://api.vietqr.io/img/TCB.png',
  },
  {
    _id: '2',
    name: 'Ngân hàng TMCP Á Châu',
    value: 'ACB',
    shortName: 'ACB',
    icon: 'https://api.vietqr.io/img/ACB.png',
  },
  {
    _id: '47',
    name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng',
    value: 'VPB',
    shortName: 'VPBank',
    icon: 'https://api.vietqr.io/img/VPB.png',
  },
  {
    _id: '39',
    name: 'Ngân hàng TMCP Tiên Phong',
    value: 'TPB',
    shortName: 'TPBank',
    icon: 'https://api.vietqr.io/img/TPB.png',
  },
  {
    _id: '36',
    name: 'Ngân hàng TMCP Sài Gòn Thương Tín',
    value: 'STB',
    shortName: 'Sacombank',
    icon: 'https://api.vietqr.io/img/STB.png',
  },
  {
    _id: '12',
    name: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh',
    value: 'HDB',
    shortName: 'HDBank',
    icon: 'https://api.vietqr.io/img/HDB.png',
  },
  {
    _id: '44',
    name: 'Ngân hàng TMCP Bản Việt',
    value: 'VCCB',
    shortName: 'VietCapitalBank',
    icon: 'https://api.vietqr.io/img/VCCB.png',
  },
  {
    _id: '31',
    name: 'Ngân hàng TMCP Sài Gòn',
    value: 'SCB',
    shortName: 'SCB',
    icon: 'https://api.vietqr.io/img/SCB.png',
  },
  {
    _id: '45',
    name: 'Ngân hàng TMCP Quốc tế Việt Nam',
    value: 'VIB',
    shortName: 'VIB',
    icon: 'https://api.vietqr.io/img/VIB.png',
  },
  {
    _id: '35',
    name: 'Ngân hàng TMCP Sài Gòn - Hà Nội',
    value: 'SHB',
    shortName: 'SHB',
    icon: 'https://api.vietqr.io/img/SHB.png',
  },
  {
    _id: '10',
    name: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam',
    value: 'EIB',
    shortName: 'Eximbank',
    icon: 'https://api.vietqr.io/img/EIB.png',
  },
  {
    _id: '22',
    name: 'Ngân hàng TMCP Hàng Hải',
    value: 'MSB',
    shortName: 'MSB',
    icon: 'https://api.vietqr.io/img/MSB.png',
  },
  {
    _id: '53',
    name: 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank',
    value: 'CAKE',
    shortName: 'CAKE',
    icon: 'https://api.vietqr.io/img/CAKE.png',
  },
  {
    _id: '54',
    name: 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank',
    value: 'Ubank',
    shortName: 'Ubank',
    icon: 'https://api.vietqr.io/img/UBANK.png',
  },
  {
    _id: '34',
    name: 'Ngân hàng TMCP Sài Gòn Công Thương',
    value: 'SGICB',
    shortName: 'SaigonBank',
    icon: 'https://api.vietqr.io/img/SGICB.png',
  },
  {
    _id: '3',
    name: 'Ngân hàng TMCP Bắc Á',
    value: 'BAB',
    shortName: 'BacABank',
    icon: 'https://api.vietqr.io/img/BAB.png',
  },
  {
    _id: '30',
    name: 'Ngân hàng TMCP Đại Chúng Việt Nam',
    value: 'PVCB',
    shortName: 'PVcomBank',
    icon: 'https://api.vietqr.io/img/PVCB.png',
  },
  {
    _id: '27',
    name: 'Ngân hàng Thương mại TNHH MTV Đại Dương',
    value: 'Oceanbank',
    shortName: 'Oceanbank',
    icon: 'https://api.vietqr.io/img/OCEANBANK.png',
  },
  {
    _id: '24',
    name: 'Ngân hàng TMCP Quốc Dân',
    value: 'NCB',
    shortName: 'NCB',
    icon: 'https://api.vietqr.io/img/NCB.png',
  },
  {
    _id: '37',
    name: 'Ngân hàng TNHH MTV Shinhan Việt Nam',
    value: 'SHBVN',
    shortName: 'ShinhanBank',
    icon: 'https://api.vietqr.io/img/SHBVN.png',
  },
  {
    _id: '1',
    name: 'Ngân hàng TMCP An Bình',
    value: 'ABB',
    shortName: 'ABBANK',
    icon: 'https://api.vietqr.io/img/ABB.png',
  },
  {
    _id: '41',
    name: 'Ngân hàng TMCP Việt Á',
    value: 'VAB',
    shortName: 'VietABank',
    icon: 'https://api.vietqr.io/img/VAB.png',
  },
  {
    _id: '23',
    name: 'Ngân hàng TMCP Nam Á',
    value: 'NAB',
    shortName: 'NamABank',
    icon: 'https://api.vietqr.io/img/NAB.png',
  },
  {
    _id: '29',
    name: 'Ngân hàng TMCP Xăng dầu Petrolimex',
    value: 'PGB',
    shortName: 'PGBank',
    icon: 'https://api.vietqr.io/img/PGB.png',
  },
  {
    _id: '46',
    name: 'Ngân hàng TMCP Việt Nam Thương Tín',
    value: 'VIETBANK',
    shortName: 'VietBank',
    icon: 'https://api.vietqr.io/img/VIETBANK.png',
  },
  {
    _id: '5',
    name: 'Ngân hàng TMCP Bảo Việt',
    value: 'BVB',
    shortName: 'BaoVietBank',
    icon: 'https://api.vietqr.io/img/BVB.png',
  },
  {
    _id: '33',
    name: 'Ngân hàng TMCP Đông Nam Á',
    value: 'SEAB',
    shortName: 'SeABank',
    icon: 'https://api.vietqr.io/img/SEAB.png',
  },
  {
    _id: '52',
    name: 'Ngân hàng Hợp tác xã Việt Nam',
    value: 'COOPBANK',
    shortName: 'COOPBANK',
    icon: 'https://api.vietqr.io/img/COOPBANK.png',
  },
  {
    _id: '20',
    name: 'Ngân hàng TMCP Bưu Điện Liên Việt',
    value: 'LPB',
    shortName: 'LienVietPostBank',
    icon: 'https://api.vietqr.io/img/LPB.png',
  },
  {
    _id: '19',
    name: 'Ngân hàng TMCP Kiên Long',
    value: 'KLB',
    shortName: 'KienLongBank',
    icon: 'https://api.vietqr.io/img/KLB.png',
  },
  {
    _id: '55',
    name: 'Ngân hàng Đại chúng TNHH Kasikornbank',
    value: 'KBank',
    shortName: 'KBank',
    icon: 'https://api.vietqr.io/img/KBANK.png',
  },
  {
    _id: '48',
    name: 'Ngân hàng Liên doanh Việt - Nga',
    value: 'VRB',
    shortName: 'VRB',
    icon: 'https://api.vietqr.io/img/VRB.png',
  },
  {
    _id: '32',
    name: 'Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam',
    value: 'SCVN',
    shortName: 'StandardChartered',
    icon: 'https://api.vietqr.io/img/SCVN.png',
  },
  {
    _id: '25',
    name: 'Ngân hàng Nonghyup - Chi nhánh Hà Nội',
    value: 'NHB HN',
    shortName: 'Nonghyup',
    icon: 'https://api.vietqr.io/img/NHB.png',
  },
  {
    _id: '18',
    name: 'Ngân hàng TNHH Indovina',
    value: 'IVB',
    shortName: 'IndovinaBank',
    icon: 'https://api.vietqr.io/img/IVB.png',
  },
  {
    _id: '16',
    name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh',
    value: 'IBK - HCM',
    shortName: 'IBKHCM',
    icon: 'https://api.vietqr.io/img/IBK.png',
  },
  {
    _id: '51',
    name: 'Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh',
    value: 'KBHCM',
    shortName: 'KookminHCM',
    icon: 'https://api.vietqr.io/img/KBHCM.png',
  },
  {
    _id: '50',
    name: 'Ngân hàng Kookmin - Chi nhánh Hà Nội',
    value: 'KBHN',
    shortName: 'KookminHN',
    icon: 'https://api.vietqr.io/img/KBHN.png',
  },
  {
    _id: '49',
    name: 'Ngân hàng TNHH MTV Woori Việt Nam',
    value: 'WVN',
    shortName: 'Woori',
    icon: 'https://api.vietqr.io/img/WVN.png',
  },
  {
    _id: '14',
    name: 'Ngân hàng TNHH MTV HSBC (Việt Nam)',
    value: 'HSBC',
    shortName: 'HSBC',
    icon: 'https://api.vietqr.io/img/HSBC.png',
  },
  {
    _id: '6',
    name: 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam',
    value: 'CBB',
    shortName: 'CBBank',
    icon: 'https://api.vietqr.io/img/CBB.png',
  },
  {
    _id: '15',
    name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội',
    value: 'IBK - HN',
    shortName: 'IBKHN',
    icon: 'https://api.vietqr.io/img/IBK.png',
  },
  {
    _id: '7',
    name: 'Ngân hàng TNHH MTV CIMB Việt Nam',
    value: 'CIMB',
    shortName: 'CIMB',
    icon: 'https://api.vietqr.io/img/CIMB.png',
  },
  {
    _id: '8',
    name: 'DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh',
    value: 'DBS',
    shortName: 'DBSBank',
    icon: 'https://api.vietqr.io/img/DBS.png',
  },
  {
    _id: '9',
    name: 'Ngân hàng TMCP Đông Á',
    value: 'DOB',
    shortName: 'DongABank',
    icon: 'https://api.vietqr.io/img/DOB.png',
  },
  {
    _id: '11',
    name: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu',
    value: 'GPB',
    shortName: 'GPBank',
    icon: 'https://api.vietqr.io/img/GPB.png',
  },
  {
    _id: '28',
    name: 'Ngân hàng TNHH MTV Public Việt Nam',
    value: 'PBVN',
    shortName: 'PublicBank',
    icon: 'https://api.vietqr.io/img/PBVN.png',
  },
  {
    _id: '40',
    name: 'Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh',
    value: 'UOB',
    shortName: 'UnitedOverseas',
    icon: 'https://api.vietqr.io/img/UOB.png',
  },
  {
    _id: '13',
    name: 'Ngân hàng TNHH MTV Hong Leong Việt Nam',
    value: 'HLBVN',
    shortName: 'HongLeong',
    icon: 'https://api.vietqr.io/img/HLBVN.png',
  },
];
