def node_require(script)
 # Resolve script with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
   "require.resolve(
     '#{script}',
     {paths: [process.argv[1]]},
   )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!
use_modular_headers!
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

# ⬇️ uncomment wanted permissions
setup_permissions([
  # 'Calendars',
  'Camera',
  'Contacts',
  'FaceID',
  'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
  'Reminders',
])


target 'moneykeeper' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Uncomment this line if you're not using auto-linking
  # pod 'WatermelonDB', path: '../node_modules/@nozbe/watermelondb'

  # WatermelonDB dependency, should not be needed on modern React Native
  # (please file an issue if this causes issues for you)
  # pod 'React-jsi', path: '../node_modules/react-native/ReactCommon/jsi', modular_headers: true

  # WatermelonDB dependency
  pod 'simdjson', path: '../node_modules/@nozbe/simdjson'
  
  # @react-native-menu/menu (fabric+swift requirements)
  pod 'React-Fabric', :path => '../node_modules/react-native/ReactCommon'
  pod 'React-graphics', :path => '../node_modules/react-native/ReactCommon/react/renderer/graphics'
  pod 'React-utils', :path => '../node_modules/react-native/ReactCommon/react/utils'
  pod 'React-debug', :path => '../node_modules/react-native/ReactCommon/react/debug'

  # Firebase
  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'
  pod 'RNFBDatabase', :path => '../node_modules/@react-native-firebase/database'

  target 'moneykeeperTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
