ENV['RCT_NEW_ARCH_ENABLED'] = '1'

require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  require Pod::Executable.execute_command('node', ['-p',
     "require.resolve('#{script}', {paths: [process.argv[1]]})", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '15.1' # Đảm bảo min iOS phù hợp với RN 0.83
prepare_react_native_project!

# 1. Cấu hình Firebase Static Framework
$RNFirebaseAsStaticFramework = true
use_modular_headers!

setup_permissions([
  'Camera', 'Contacts', 'FaceID', 'Notifications', 'PhotoLibrary', 'PhotoLibraryAddOnly', 'Reminders',
])

target 'moneykeeper' do
  use_expo_modules!
 
  if ENV['EXPO_USE_COMMUNITY_AUTOLINKING'] == '1'
    config_command = ['node', '-e', "process.argv=['', '', 'config'];require('@react-native-community/cli').run()"];
  else
    config_command = [
      'node',
      '--no-warnings',
      '--eval',
      'require(require.resolve(\'expo-modules-autolinking\', { paths: [require.resolve(\'expo/package.json\')] }))(process.argv.slice(1))',
      'react-native-config',
      '--json',
      '--platform',
      'ios'
    ]
  end
 
  config = use_native_modules!(config_command)

  # 2. Quan trọng cho Swift & Firebase
  use_frameworks! :linkage => :static

  # 3. Cấu hình React Native với New Arch
  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => true,
    :fabric_enabled => true # Bật để sửa lỗi "No such module 'ReactAppDependencyProvider'"
  )

  # 4. Các thư viện đặc thù không autolink hoàn toàn hoặc cần config riêng
  pod 'simdjson', path: '../node_modules/@nozbe/simdjson'
  
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

  post_install do |installer|
    # 5. Đảm bảo config hệ thống của React Native được thực thi
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Fix lỗi build "Double quoted include" thường gặp khi dùng Swift + Static Frameworks
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end