export let defaultValues = {
  amount: 0,
  toAmount: 0,
  dateTimeAt: new Date(),
  closingAmount: 0,
  categoryId: '',
  accountId: '',
  descriptions: '',
  location: '',
  eventName: '',
  payFor: '',
  relatedPerson: '',
  payee: '',
  giver: '',
  fee: 0,
  feeType: '',
  excludeReport: 0,
  attachment: '',
  userId: '',
};
